// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"database/sql"
)

type Product struct {
	ID          interface{}     `json:"id"`
	Name        sql.NullString  `json:"name"`
	Description sql.NullString  `json:"description"`
	Image       sql.NullString  `json:"image"`
	Price       sql.NullFloat64 `json:"price"`
	Rating      sql.NullFloat64 `json:"rating"`
	Category    sql.NullString  `json:"category"`
	Stock       sql.NullInt64   `json:"stock"`
	Available   sql.NullBool    `json:"available"`
}
