// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteProduct(ctx context.Context, id interface{}) error
	GetProduct(ctx context.Context, id interface{}) (Product, error)
	GetProducts(ctx context.Context) ([]Product, error)
	InsertProduct(ctx context.Context, arg InsertProductParams) (sql.Result, error)
	ListProducts(ctx context.Context) ([]Product, error)
	UpdateProductAvailability(ctx context.Context, arg UpdateProductAvailabilityParams) (sql.Result, error)
	UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) (sql.Result, error)
	UpdateProductRating(ctx context.Context, arg UpdateProductRatingParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
