// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :execresult
INSERT INTO products (
    name ,description ,image, price,rating , available , category, stock
) VALUES (
  ?,?,?,?,?,?,?,?
)
`

type CreateProductParams struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Image       string  `json:"image"`
	Price       float64 `json:"price"`
	Rating      float64 `json:"rating"`
	Available   bool    `json:"available"`
	Category    string  `json:"category"`
	Stock       int64   `json:"stock"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Image,
		arg.Price,
		arg.Rating,
		arg.Available,
		arg.Category,
		arg.Stock,
	)
}

const deleteProduct = `-- name: DeleteProduct :execresult
DELETE FROM products
WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProduct, id)
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, price, description, image, available, stock, category, rating FROM products
WHERE id = ?
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Description,
		&i.Image,
		&i.Available,
		&i.Stock,
		&i.Category,
		&i.Rating,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT id, name, price, description, image, available, stock, category, rating FROM products
ORDER BY name
`

func (q *Queries) GetProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Description,
			&i.Image,
			&i.Available,
			&i.Stock,
			&i.Category,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price, description, image, available, stock, category, rating FROM products
LIMIT 5
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Description,
			&i.Image,
			&i.Available,
			&i.Stock,
			&i.Category,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductAvailability = `-- name: UpdateProductAvailability :execresult
UPDATE products SET available = ? WHERE id  = ?
`

type UpdateProductAvailabilityParams struct {
	Available bool  `json:"available"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateProductAvailability(ctx context.Context, arg UpdateProductAvailabilityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProductAvailability, arg.Available, arg.ID)
}

const updateProductPrice = `-- name: UpdateProductPrice :execresult
UPDATE products SET price = ? WHERE id  = ?
`

type UpdateProductPriceParams struct {
	Price float64 `json:"price"`
	ID    int64   `json:"id"`
}

func (q *Queries) UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProductPrice, arg.Price, arg.ID)
}

const updateProductRating = `-- name: UpdateProductRating :execresult
UPDATE products SET rating = ? WHERE id  = ?
`

type UpdateProductRatingParams struct {
	Rating float64 `json:"rating"`
	ID     int64   `json:"id"`
}

func (q *Queries) UpdateProductRating(ctx context.Context, arg UpdateProductRatingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProductRating, arg.Rating, arg.ID)
}
