// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error)
	DeleteProduct(ctx context.Context, id int64) (sql.Result, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProducts(ctx context.Context) ([]Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	UpdateProductAvailability(ctx context.Context, arg UpdateProductAvailabilityParams) (sql.Result, error)
	UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) (sql.Result, error)
	UpdateProductRating(ctx context.Context, arg UpdateProductRatingParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
