// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCart(ctx context.Context) (sql.Result, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error)
	DeleteCart(ctx context.Context, cartID string) (sql.Result, error)
	DeleteCartItems(ctx context.Context, cartID string) (sql.Result, error)
	DeleteProduct(ctx context.Context, id int64) (sql.Result, error)
	GetCart(ctx context.Context, id int64) (Cart, error)
	GetCartItem(ctx context.Context, arg GetCartItemParams) (CartItem, error)
	GetCartItems(ctx context.Context, cartID string) ([]GetCartItemsRow, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProducts(ctx context.Context) ([]Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	SaveCartItems(ctx context.Context, arg SaveCartItemsParams) (sql.Result, error)
	UpdateCartItems(ctx context.Context, arg UpdateCartItemsParams) (sql.Result, error)
	UpdateProductAvailability(ctx context.Context, arg UpdateProductAvailabilityParams) (sql.Result, error)
	UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) (sql.Result, error)
	UpdateProductRating(ctx context.Context, arg UpdateProductRatingParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
